### PR TITLE
Add a "Satellite" profile with exaggerated latency

### PR DESCRIPTION
**Pull request by riking**
This can help application developers detect extraneous round-trips they are making.

### CODE REVIEW

**Comment by tylertreat** [comment]
Do you have a source for these numbers?

**Comment by shortdudey123** [comment]
This source says ~1000ms latency (http://www.vsat-systems.com/satellite-internet-explained/latency.html), however, i would agree more with the 1500ms latency from experience.

**Comment by tylertreat** [comment]
Ok, seems reasonable. Just wanted to double check.

**Comment by riking** [comment]
I don't have a source for the packet loss, I just copied the number from one of the other profiles. No clue what the real packet loss is like.

**Pull request merged**
