### PR TITLE
Add ipv6 destination support on Linux

### PR DESCRIPTION
**Pull request by roman-kashitsyn**
Now it's possible to specify IPv6 address as a destination using the `--ipv6` command line option:
```
comcast --packet-loss=20% --ipv6 --target-addr=2001:db8::1 --target-proto=tcp --target-port=80
```

### CODE REVIEW

**Comment by Term1nal** [comment]
Looks good! :3

**Comment by tylertreat** [comment]
Thanks!

**Comment by roman-kashitsyn** [comment]
> Split the --target-addr flag into -target-addr6 and -target-addr4

I think it's a good idea - we can just add `--target-addr6` and leave `--target-addr` for ipv4 to keep backward compatibility. I'll also remove the need to specify `--ipv6` in the `stop` mode - we can just run both `iptables` and `ip6tables` (if present) to list rules.

**Comment by Term1nal** [comment]
Yes exactly, that would be best in my opinion, and more consistent with the current usage.

**Pull request merged**
