### PR TITLE
added a table of simulated network conditions to the markdown

### PR DESCRIPTION
**Pull request by jujhars13**
I added a guide table with network condition values to plug into Comcast.  I think it will be useful. Hopefully more people with real multi-network experience can add some more profiles.

J

### CODE REVIEW

**Comment by paulirish** [comment]
hi @jujhars13 where did you source the data for this table? 

Just curious :)

**Comment by jujhars13** [comment]
A bit is from a research paper that I googled but can no longer find (I should have cited it)
So it's mostly from Chrome's dev tools and a couple of my friend's who are Cisco WAN nerds.  

Have you got any research backed figures?  I'll then submit a PR that will actually add these as profiles into comcast itself.

**Comment by paulirish** [comment]
Well I helped develop the presets for Chrome's devtools. :)
I also can't give you a good citation but we've gotten a lot of experts to
look these over and revised them once. Seems decent for now. :)


​

**Comment by tylertreat** [comment]
As a side note: there is [some confusion](https://github.com/tylertreat/Comcast/issues/15) on the packet-loss figures since Comcast currently takes a percentage (e.g. 0.1 will drop 10% of packets), but that doesn't align with the profile table.

**Pull request merged**
