### PR TITLE
Added manpage

### PR DESCRIPTION
**Pull request by ryankearney**
Added a shitty manpage (I don't even know how to create manages I had to Google it and this is what I came up with) to simulate shitty customer service. Fixes tylertreat/Comcast#1

### CODE REVIEW

**Comment by ryankearney** [comment]
@shortdudey123 I wanted to mimic the theme of this project sooooo, both?

**Comment by shortdudey123** [comment]
Fair enough, but maybe add some semi useful stuff :p

**Comment by ryankearney** [comment]
Ah yes, but the goal was to simulate shitty customer service. Trying to solve tylertreat/Comcast#1

**Comment by tylertreat** [comment]
Despite the name, this tool is actually not a joke. I wrote it to test systems under extreme network conditions. The name was just made in jest.

**Pull request closed without merging**
