### PR TITLE
codebeat badge

### PR DESCRIPTION
**Pull request by korzonek**
Is it fine to add codebeat badge to README? 

codebeat is automated code review tool for Swift,Ruby,Go & Python that helps get instant feedback on code quality. 

"Quick wins" suggested by codebeat could be a nice candidate for a pull request and help other developers become contributors.

FYI. To be fully open and honest. I'm co-founder of codebeat.

### CODE REVIEW

**Comment by Term1nal** [comment]
I mean, it doesn't really hurt anything to add it. Though looking through the suggestions by the tool, a lot of these seem rather pointless IMHO.

**Comment by Term1nal** [comment]
I think this is a bot. Look at the dude's issues. It's this same copy/paste PR. Trying to spread his company around on the backs of other people's projects.

**Comment by shortdudey123** [comment]
agree with @Term1nal 
Most of the suggestions that come back, i disable in rubocop when i do ruby stuff

Not opposed though, just don't see the helpfulness of the current suggestion set

**Comment by korzonek** [comment]
@Term1nal @shortdudey123 I didn't want to spam you. I just wanted to encourage you to give a try to codebeat. It is my baby. I put a lot of love into it.

We launched in January with support for Ruby and Go and in February we added support for Swift and Python. 

We build all algorithms on our own. Please give a try to codebeat and share with me what we could improve in order to bring value to you.

BTW... please check https://help.codebeat.co/docs/how-is-codebeat-different to learn more about our approach and intentions.

**Pull request closed without merging**
